-- Part 3 Task 3

DELIMITER // 

DROP FUNCTION IF EXISTS FIBONACCI//
CREATE FUNCTION FIBONACCI(counter INT UNSIGNED)
RETURNS INT UNSIGNED DETERMINISTIC
BEGIN
	DECLARE fibo1 INT UNSIGNED DEFAULT 0;
	DECLARE fibo2 INT UNSIGNED DEFAULT 1;
	DECLARE fibo3 INT UNSIGNED DEFAULT 1;
	WHILE counter != 0 DO
		SET fibo1 = fibo2;
		SET fibo2 = fibo3;
		SET fibo3 = fibo1 + fibo2;
		SET counter = counter - 1;
	END WHILE;
	RETURN fibo1;
END//

DELIMITER ;

SELECT FIBONACCI(10) as Fibonacci;
